DROP TABLE r_keszlet CASCADE CONSTRAINTS;
DROP TABLE r_kifizetes CASCADE CONSTRAINTS;
DROP TABLE r_rendeles_tetel CASCADE CONSTRAINTS;
DROP TABLE r_rendeles CASCADE CONSTRAINTS;
DROP TABLE r_termek CASCADE CONSTRAINTS;
DROP TABLE r_ugyfel CASCADE CONSTRAINTS;
DROP TABLE r_raktar CASCADE CONSTRAINTS;

DROP SEQUENCE r_rendeles_seq;